### ISSUE TITLE
Cactbot raidboss overlay does not work with logitech keybinds

### ISSUE THREAD

**Issue by exKitsune** [ngld/OverlayPlugin#146]
Using the latest ACT, overlayplugin release, and cactbot release, and I'm using LGS instead of Logitech HUB.

Normal behavior is mouse keybinds will work upon alt-tabbing into the game.
With a cactbot overlay, alt-tabbing into the game will confuse logitech and the keybinds will not work.
The "fix" is to click the main ACT window and then click into FFXIV in order for the keybinds to work.

My OverlayPlugin.dll window looks like this 
![image](https://user-images.githubusercontent.com/15070397/88987255-57a2a300-d2a3-11ea-94f9-90bf5d3b21a4.png)
The "cact" overlay is Cactbot Raidboss preset.
If I remove the "cact" overlay, then I get normal behavior once again.

Another note is that clicking the cact ACTWS compatibility returns the following error message in the log, if this is relevant
```
[7/30/2020 8:30:53 PM] Error: Error checking html rel dir: file:///C:/Users/fruit/AppData/Roaming/ACT%20Plugins/cactbot-0.18.4/cactbot/ui/raidboss/raidboss.html?timeline=1&alerts=0&HOST_PORT=ws://127.0.0.1/fake/: System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Cactbot.CactbotEventSource.GetUserConfigDirAndFiles(String source, String& config_dir, Dictionary`2& local_files)
[7/30/2020 8:30:53 PM] Info: cact: BrowserConsole: CSS cannot be loaded from `file:` URLs unless they end in a `.css` file extension. (Source: , Line: 0)
```

**Comment by ngld** [comment]
The error isn't relevant since that's the expected outcome. The option explicitly mentions that you should never use ACTWS compatibility with any overlay that was built for OverlayPlugin (since it breaks those).

My guess (as per the discussion on Discord) is that Logitech is confused by the overlay windows and doesn't realize that the game is focused. Windows's window stack is a bit weird in that regard. If you configure your macros in Logitech's software to work for both FFXIV and ACT (pretend ACT is a game), they should work as expected.

**Comment by ngld** [comment]
This was solved on Discord.
