### ISSUE TITLE
Unhandled Exception in ACT

### ISSUE THREAD

**Issue by skullfishyy** [ngld/OverlayPlugin#147]
Hello!,
I've been getting this error and i've tried running as admin, downloaded and redownloaded, checked firewall, etc.  Any help would be greatly appreciated!

System.IO.FileNotFoundException - Could not load file or assembly 'CefSharp, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The system cannot find the file specified.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at RainbowMage.OverlayPlugin.PluginLoader.<FinishInit>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RainbowMage.OverlayPlugin.PluginLoader.<Initialize>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

System.Windows.Forms.Control, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

**Comment by skullfishyy** [comment]
Just deleted the entire folder in AppData and reinstalled ACT.

**Comment by ngld** [comment]
That error indicates that files from your `%AppData%\Advanced Combat Tracker\OverlayPluginCef` folder are missing. OverlayPlugin automatically downloads the files again if the folder is missing. The next time you see this error, close ACT, delete said folder and open ACT again to fix the issue (should be much faster than reinstalling).

Some background as to why this happens: OverlayPlugin assumes that the folder is fine if it exists since I never expected someone to delete individual files from inside the folder. I suppose some trigger-happy AV or other "cleaning" software is the cause. Either way, the next OverlayPlugin version will properly handle this error and automatically re-download the files if necessary.
