### ISSUE TITLE
Zoom is capped at 400

### ISSUE THREAD

**Issue by MikeZTM** [ngld/OverlayPlugin#197]
For super high resolution HiDPI screens the overlay zoom is usually needed to set at 600 or more.
This can be done via editing the json config file but can not be done in the GUI directly.
Should be a easy change to make zoom a type in value instead of a slider and allow much larger values.

**Comment by MikeZTM** [comment]
And this will cause the GUI to complain about it:

Error: InitPlugin: System.ArgumentOutOfRangeException: Value of '600' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.TrackBar.set_Value(Int32 value)
   at RainbowMage.OverlayPlugin.Overlays.MiniParseConfigPanel.SetupControlProperties()
   at RainbowMage.OverlayPlugin.Overlays.MiniParseConfigPanel..ctor(TinyIoCContainer container, MiniParseOverlay overlay)
   at RainbowMage.OverlayPlugin.Overlays.MiniParseOverlay.CreateConfigControl()
   at RainbowMage.OverlayPlugin.ControlPanel.AddConfigTab(IOverlay overlay)
   at RainbowMage.OverlayPlugin.ControlPanel.InitializeOverlayConfigTabs()
   at RainbowMage.OverlayPlugin.PluginMain.<InitPlugin>b__25_9()
