### ISSUE TITLE
Unhandled exception when closing FFXIV

### ISSUE THREAD

**Issue by quisquous** [ngld/OverlayPlugin#23]
When closing FFXIV, I got this exception.  I thought there was a try block around UpdateEnmity, but it looks like it needs to extend around isValid as well.

Maybe it's a design smell to have those side effects from isValid.

```
---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.ComponentModel.Win32Exception - Only part of a ReadProcessMemory or WriteProcessMemory request was completed
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at RainbowMage.OverlayPlugin.EventSources.FFXIVMemory.SigScan(String pattern, Int32 offset, Boolean rip_addressing)
   at RainbowMage.OverlayPlugin.EventSources.EnmityMemory.GetPointerAddress()
   at RainbowMage.OverlayPlugin.EventSources.EnmityMemory.IsValid()
   at RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.UpdateEnmity(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

System.Diagnostics.NtProcessManager, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
---------------------------
OK   
---------------------------
```

**Comment by ngld** [comment]
I think this exception should just be caught in `SigScan`. Since any call to that method can potentially throw such that exception (i.e. if the game crashes while we're reading a value).
The same is true for any other method that calls `NativeMethods.ReadProcessMemory`. If this exception is caught, it should just abort and return an error code / `false`.

For now, the PR is a good stopgap measure though and will work as far as I can see until some new code uses `EnmityMemory`. The only obvious downside seems to be that users will see an error being logged although I wouldn't call this an error. It's natural for the memory reading to fail if the program being read is exiting.
