### ISSUE TITLE
after the latest ACT update i keep getting this Error

### ISSUE THREAD

**Issue by McxNuggy** [ngld/OverlayPlugin#233]
---------------------------
Fatal Error - Unhandled Exception
---------------------------
An unhandled exception has occurred.  ACT may close.
Press Ctrl-C to copy this MessageBox.

System.InvalidOperationException - Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)

   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()

   at RainbowMage.OverlayPlugin.OverlayZCorrector.EnsureOverlaysAreOverGame(Object _)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.TimerQueueTimer.CallCallback()

   at System.Threading.TimerQueueTimer.Fire()

   at System.Threading.TimerQueue.FireNextTimers()

System.ThrowHelper, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
---------------------------
OK   
---------------------------

**Comment by McxNuggy** [comment]
figured out the issue, dx11 zombie process
