### ISSUE TITLE
Error on ACT Startup

### ISSUE THREAD

**Issue by Onryou5** [ngld/OverlayPlugin#66]
[12/10/2019 12:34:21 AM] Error: System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\libs\x64' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at RainbowMage.OverlayPlugin.Updater.CurlWrapper.Init(String pluginDirectory)
   at RainbowMage.OverlayPlugin.PluginLoader.<Initialize>d__7.MoveNext()
[12/10/2019 12:34:21 AM] Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin
[12/10/2019 12:34:22 AM] Info: InitPlugin: Initialized.
[12/10/2019 12:34:22 AM] Error: LoadAddons: System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[12/10/2019 12:34:22 AM] Error: LoadAddons: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

Getting this every time I startup ACT. I've tried reinstalling and making sure I have the latest version, but it doesn't seem to work.

**Comment by Onryou5** [comment]
After a clean install and deleting everything including registry keys, I don't get the string of errors in ACT, but this does pop up when I launch ACT.
![image](https://user-images.githubusercontent.com/58725080/70516540-05322d80-1aec-11ea-8c73-36adc0ec6110.png)
