### ISSUE TITLE
Overlay Plugin Error Log

### ISSUE THREAD

**Issue by Crescr** [ngld/OverlayPlugin#74]
The following error log is output to the lower log window.
The overlay itself is working.
Causes and occur situation is unknown.

OverlayPlugin 0.11.6.0
DFAPlugin 2.2.0.0

[2019/12/25 10:42:06] Info: InitPlugin: PluginDirectory = C:\ACT\Plugin\Overlay
[2019/12/25 10:42:06] Info: InitPlugin: Initialized.
[2019/12/25 10:42:08] Info: DFA: GetStructures: URL: https://qitana.github.io/ACT_DFAPlugin/data/structures.json
[2019/12/25 10:42:08] Info: DFA: Started.
[2019/12/25 10:42:08] Info: LoadAddons: DFAPlugin.dll: Initialized
[2019/12/25 10:42:10] Info: DFA: Handled: DataSubscription
[2019/12/25 10:43:16] Error: UpdateEnmity: System.ComponentModel.Win32Exception (0x80004005): Only part of a ReadProcessMemory or WriteProcessMemory request was completed
   at  System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at  System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at  System.Diagnostics.Process.get_MainModule()
   at  RainbowMage.OverlayPlugin.EventSources.FFXIVMemory.SigScan(String pattern, Int32 offset, Boolean rip_addressing)
   at  RainbowMage.OverlayPlugin.EventSources.EnmityMemory.GetPointerAddress()
   at  RainbowMage.OverlayPlugin.EventSources.EnmityMemory.IsValid()
   at  RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.UpdateEnmity(Object state)

**Comment by ngld** [comment]
Does this still happen with the latest release?

**Comment by Crescr** [comment]
> Does this still happen with the latest release?

It no longer occurs frequently.
But it still happens sometimes.

**Comment by Crescr** [comment]
Just today of overlay log.

OverlayPlugin 0.12.1
DFAPlugin 2.2.0.0
FFXIV_ACT_Plugin.dll 2.0.4.9

* FFXIV_ACT_Plugin.dll 2.0.4.13 uses 2.0.4.9 because of the phenomenon that the CPU usage is high.

[2020/01/06 10:42:18] Info: InitPlugin: PluginDirectory = C:\ACT\Plugin\Overlay
[2020/01/06 10:42:18] Info: InitPlugin: Initialized.
[2020/01/06 10:42:28] Info: DFA: GetStructures: URL: https://qitana.github.io/ACT_DFAPlugin/data/structures.json
[2020/01/06 10:42:29] Info: DFA: Started.
[2020/01/06 10:42:29] Info: LoadAddons: DFAPlugin.dll: Initialized
[2020/01/06 10:42:31] Info: DFA: Handled: DataSubscription
[2020/01/06 10:46:47] Error: Failed to memory scan: charmapAddress,enmityAddress,aggroAddress,targetAddress.
[2020/01/06 10:46:47] Error: UpdateEnmity: System.ComponentModel.Win32Exception (0x80004005): Only part of a ReadProcessMemory or WriteProcessMemory request was completed
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at RainbowMage.OverlayPlugin.EventSources.FFXIVMemory.SigScan(String pattern, Int32 offset, Boolean rip_addressing)
   at RainbowMage.OverlayPlugin.EventSources.EnmityMemory.GetPointerAddress()
   at RainbowMage.OverlayPlugin.EventSources.EnmityMemory.IsValid()
   at RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.UpdateEnmity(Object state)
[2020/01/06 10:46:47] Error: UpdateEnmity: System.ComponentModel.Win32Exception (0x80004005): Only part of a ReadProcessMemory or WriteProcessMemory request was completed
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at RainbowMage.OverlayPlugin.EventSources.FFXIVMemory.SigScan(String pattern, Int32 offset, Boolean rip_addressing)
   at RainbowMage.OverlayPlugin.EventSources.EnmityMemory.GetPointerAddress()
   at RainbowMage.OverlayPlugin.EventSources.EnmityMemory.IsValid()
   at RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.UpdateEnmity(Object state)
[2020/01/06 14:27:23] Info: DFA: Queued [0/78]
[2020/01/06 14:27:23] Info: DFA: Queued: WaitList:0 WaitTime:0 Tank:0/0 Healer:0/0 DPS:0/0
[2020/01/06 14:27:23] Info: DFA: Matched [0/78]
[2020/01/06 14:27:26] Info: DFA: Matched: Tank:14/127 Healer:0/0 DPS:128/6 NonRole:7/8
[2020/01/06 14:27:27] Info: DFA: Matched: Tank:14/127 Healer:0/0 DPS:128/6 NonRole:8/8
[2020/01/06 14:27:30] Info: DFA: ZoneChanged: 375, the Striking Tree (Extreme)
[2020/01/06 14:28:33] Info: DFA: Canceled

**Comment by mooondark** [comment]
It happens when you leave FFXIV and ACT is still on. Got the same issue with Enmity.

```[06/01/2020 13:27:17] Error: Failed to memory scan: charmapAddress,enmityAddress,aggroAddress,targetAddress.
[06/01/2020 13:27:18] Error: UpdateEnmity: System.ArgumentException: Un processus ayant l'ID 10164 n'est pas exécuté.
   à System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   à RainbowMage.OverlayPlugin.EventSources.FFXIVMemory.FindProcess()
   à RainbowMage.OverlayPlugin.EventSources.FFXIVMemory.IsValid()
   à RainbowMage.OverlayPlugin.EventSources.EnmityMemory.IsValid()
   à RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.UpdateEnmity(Object state)
```

**Comment by ngld** [comment]
Just for the record: As long as the error only occurs occasionally, it's safe to ignore. Each time you see this error, memory reading failed for some reason (usually because the game was just launched or is closing). Enmity data is updated every 100ms by default so it's not an issue if one or two of those updates fail.

I should probably add a filter which only logs an error if the error persists for a second or more.

**Comment by Crescr** [comment]
This error has never occurred in 0.13.2.
Probably it has been fixed successfully.

Sorry for the late report.
