### ISSUE TITLE
Exception when quitting game

### ISSUE THREAD

**Issue by quisquous** [ngld/OverlayPlugin#87]
```
[1/4/2020 10:17:25 AM] Error: UpdateEnmity: System.ArgumentException: Process with an Id of 15592 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at RainbowMage.OverlayPlugin.EventSources.FFXIVMemory.FindProcess()
   at RainbowMage.OverlayPlugin.EventSources.FFXIVMemory.IsValid()
   at RainbowMage.OverlayPlugin.EventSources.EnmityMemory.GetPointerAddress()
   at RainbowMage.OverlayPlugin.EventSources.EnmityMemory.IsValid()
   at RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.UpdateEnmity(Object state)
```

Just saw this and wanted to mention it before I forgot, as it seems like something that maybe could be avoided or caught.

**Comment by ngld** [comment]
Should be fixed by https://github.com/ngld/OverlayPlugin/commit/0c1869b2eef587d5e1e54bacea491bd320d83840
