### ISSUE TITLE
Booting up issue

### ISSUE THREAD

**Issue by Lokidoki8017** [ngld/OverlayPlugin#99]
[27/01/2020 22:12:17] Info: InitPlugin: PluginDirectory = E:\Advanced Combat Tracker\OverlayPlugin
[27/01/2020 22:12:17] Info: InitPlugin: Initialized.
[27/01/2020 22:12:19] Error: Got a subscription for missing event "onUserFileChanged"!
[27/01/2020 22:12:19] Error: Got a subscription for missing event "onForceReload"!
[27/01/2020 22:12:19] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadUser"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[27/01/2020 22:12:19] Error: JS Handler call failed: System.Exception: Tried to call missing handler "cactbotLoadData"!
   at RainbowMage.OverlayPlugin.EventDispatcher.CallHandler(JObject e)
   at RainbowMage.OverlayPlugin.EventDispatcher.ProcessHandlerMessage(IEventReceiver receiver, String data)
[27/01/2020 22:12:19] Info: Raid: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'detail' of null (Source: file:///E:/Advanced%20Combat%20Tracker/cactbot/resources/user_config.js, Line: 35)

**Comment by ngld** [comment]
These error messages appear if you use a Cactbot overlay without enabling `CactbotOverlay.dll` or if you didn't restart ACT after enabling `CactbotOverlay.dll`.
